[package]
name = "elytrad"
version = "0.0.0"
edition = "2021"

[dependencies]
base62 = "2.2.1"
bytes = "1.10.1"
serde_cbor = "0.11.2"
sled = "0.34.7"
snowflake = { version = "0.1.0", path = "../snowflake" }
xxhash-rust = { version = "0.8.15", default-features = false, features = [
    "xxh64",
] }
