[package]
name = "elytrad"
version = "0.0.0"
edition = "2021"

[dependencies]
base62 = "2.2.1"
once_cell = "1.21.3"
portable-atomic = "1.11.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
rayon = "1.10.0"

[[bench]]
name = "id"
harness = false
